spring.application.name=vote
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VoteSystem;encrypt=true;trustServerCertificate=true

spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:Esun@123456}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true